# Site settings
title: MayOne.US
email: info@mayone.us
description: "MayOne.US - SuperPAC to end all SuperPACs. Join our effort to win a Congress committed to reforming the influence of money in Politics."
baseurl: /homepage_redesign

# Build settings
encoding: utf-8
markdown: kramdown
permalink: pretty

exclude: ["Vagrantfile", "bootstrap.sh", "start.sh"]
